apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m

    route:
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h
      receiver: 'discord'

    receivers:
    - name: 'discord'
      webhook_configs:
      - url: '${DISCORD_WEBHOOK_URL}'  # Using same webhook as notifications
        send_resolved: true
        title: '{{ template "discord.title" . }}'
        message: '{{ template "discord.message" . }}'

    templates:
    - '/etc/alertmanager/discord.tmpl'

  discord.tmpl: |
    {{ define "discord.title" }}
    [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }}
    {{ end }}

    {{ define "discord.message" }}
    {{ if gt (len .Alerts.Firing) 0 }}
    **Alerts Firing:**
    {{ range .Alerts.Firing }}
    • {{ .Labels.severity | toUpper }}: {{ .Annotations.summary }}
      {{ .Annotations.description }}
    {{ end }}
    {{ end }}
    {{ if gt (len .Alerts.Resolved) 0 }}
    **Alerts Resolved:**
    {{ range .Alerts.Resolved }}
    • {{ .Labels.severity | toUpper }}: {{ .Annotations.summary }}
    {{ end }}
    {{ end }}
