apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'spring-boot'
        metrics_path: '/actuator/prometheus'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            regex: spring-boot-app
            action: keep
          - source_labels: [__meta_kubernetes_pod_container_port_number]
            regex: "8081"
            action: keep

      - job_name: 'mysql'
        static_configs:
          - targets: ['mysql:3306']
        metrics_path: '/metrics'
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            regex: mysql
            action: keep
