{
 "title": "MySQL Metrics",
 "tags": [ "mysql" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "MySQL Connected Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "mysql_global_status_threads_connected",
     "legendFormat": "Connected Threads"
    }
   ]
  },
  {
   "title": "MySQL InnoDB I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mysql_global_status_innodb_data_reads",
     "legendFormat": "InnoDB Data Reads"
    },
    {
     "expr": "mysql_global_status_innodb_data_writes",
     "legendFormat": "InnoDB Data Writes"
    }
   ]
  },
  {
   "title": "MySQL Buffer Pool Utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_buffer_pool_utilization",
     "legendFormat": "Buffer Pool Utilization"
    }
   ]
  },
  {
   "title": "MySQL Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysql_up", "legendFormat": "MySQL Status" }
   ]
  }
 ]
}