spring:
  datasource:
    url: jdbc:mysql://mysql:3306/spring_artifacts?createDatabaseIfNotExist=true
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:mysql}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: ${SERVER_PORT:8081}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.flywaydb: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,startup,prometheus"

# CORS Configuration
cors:
  allowed-origins:
    - https://ibm-artifact-management-platform.vercel.app
    - http://localhost:3000
    - http://localhost:5173

# Sync Configuration
nodejs:
  service:
    url: ${NODEJS_SERVICE_URL:https://nodejs-ai-service-sagarregmi2056-dev.apps.rm1.0a51.p1.openshiftapps.com}

sync:
  interval: ${SYNC_INTERVAL:300000}  # 5 minutes in milliseconds