apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: spring-boot-app
  name: spring-boot-app
spec:
  replicas: 1
  selector:
    app: spring-boot-app
    deploymentconfig: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
        deploymentconfig: spring-boot-app
    spec:
      containers:
        - image: saga99/spring-boot-service:latest  # ← Will be replaced by CD
          name: spring-boot-app
          ports:
            - containerPort: 8081
              protocol: TCP
          env:
            # Use environment variables from secrets (CD pipeline will set these)
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: SPRING_DATASOURCE_PASSWORD
            - name: SERVER_PORT
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: SERVER_PORT

            - name: NODEJS_SERVICE_URL
              value: "https://nodejs-ai-service-sagarregmi2056-dev.apps.rm1.0a51.p1.openshiftapps.com"
            - name: SYNC_INTERVAL
              value: "300000"
          # Add health checks
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 30
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
  triggers:
    - type: ConfigChange
    # REMOVE ImageChange trigger - CD pipeline handles updates