name: Spring Boot CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Spring Boot Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        working-directory: ./spring-boot-service
        run: |
          chmod +x ./mvnw
          ./mvnw clean install -DskipTests

  docker-build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -f spring-boot-service/docker/Dockerfile.spring -t saga99/spring-boot-service:${{ github.sha }} ./spring-boot-service

      - name: Push Docker image
        run: docker push saga99/spring-boot-service:${{ github.sha }}

  send-discord-notification:
    name: Send Discord Notification
    runs-on: ubuntu-latest
    needs: docker-build-and-push
    if: always()
    steps:
      - name: Get workflow status
        id: check_status
        run: |
          if [ "${{ needs.docker-build-and-push.result }}" == "success" ]; then
            echo "status=SUCCESS" >> $GITHUB_OUTPUT
            echo "color=65280" >> $GITHUB_OUTPUT  # Green
          else
            echo "status=FAILURE" >> $GITHUB_OUTPUT
            echo "color=16711680" >> $GITHUB_OUTPUT  # Red
          fi

      - name: Send Discord notification
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{
                 "username": "CI CD BOT",
                 "embeds":[
                   {
                     "title": "CI Build Status",
                     "description": "**Repository:** [${GITHUB_REPOSITORY}](${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY})\n**Branch:** `${GITHUB_REF_NAME}`\n**Commit:** `${GITHUB_SHA}`\n**Status:** `${STATUS}`\n**Workflow Run:** [View Run](${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID})\n**Docker Image:** `saga99/spring-boot-service:${GITHUB_SHA}`",
                     "color": '${COLOR}'
                   }
                 ]
               }' ${{ secrets.DISCORD_WEBHOOK_URL }}
        env:
          STATUS: ${{ steps.check_status.outputs.status }}
          COLOR: ${{ steps.check_status.outputs.color }}

